yml update

diff --git a/.github/workflows/checkov-scan.yml b/.github/workflows/checkov-scan.yml
--- a/.github/workflows/checkov-scan.yml
+++ b/.github/workflows/checkov-scan.yml
@@ -37,16 +37,16 @@ jobs:
         RESULTS="[]"
         PASSED=true
         for file in "${FILES[@]}"; do
-        if [ -n "$file" ]; then
-          OUTPUT=$(checkov -f "$file" --output json || true)
-        if [ -n "$OUTPUT" ] && [[ "$(echo "$OUTPUT" | jq '. | has(\"results\")')" == "true" ]]; then
-          if [[ "$(echo "$OUTPUT" | jq '.results.failed_checks | length')" -gt 0 ]]; then
-            PASSED=false
+          if [ -n "$file" ]; then
+            OUTPUT=$(checkov -f "$file" --output json || true)
+            if [ -n "$OUTPUT" ] && [[ "$(echo "$OUTPUT" | python -c "import sys, json; print('results' in json.loads(sys.stdin.read()))")" == "True" ]]; then
+              if [[ "$(echo "$OUTPUT" | jq '.results.failed_checks | length')" -gt 0 ]]; then
+                PASSED=false
+              fi
+              OUTPUT_ESCAPED=$(echo "$OUTPUT" | python -c "import sys, json; print(json.dumps(sys.stdin.read()))")
+              RESULTS=$(python -c "import json; a=json.loads('$RESULTS'); b=json.loads($OUTPUT_ESCAPED); a.extend(b['results']['failed_checks']); print(json.dumps(a))")
+            fi
           fi
-          OUTPUT_ESCAPED=$(echo "$OUTPUT" | python -c "import sys, json; print(json.dumps(sys.stdin.read()))")
-          RESULTS=$(python -c "import json; a=json.loads('$RESULTS'); b=json.loads($OUTPUT_ESCAPED); a.extend(b['results']['failed_checks']); print(json.dumps(a))")
-          fi
-        fi
         done
         echo "CHECKOV_OUTPUT=$RESULTS" >> $GITHUB_ENV
         echo "CHECKOV_PASSED=$PASSED" >> $GITHUB_ENV
